// Generated by Wrangler on Sat Nov 09 2024 16:19:04 GMT+0300 (Arabian Standard Time)
// by running `wrangler types`

interface Env {
  MAIN_EMAIL: any;
  ADMIN_EMAIL: any;
  RESEND_API: string;
  DATABASE_URL: string;
  R2_AUTH_KEY_SECRET:string,
  QYAM_BUCKET:R2Bucket
  CONTACT_NUMBER:string
}
